backend:
  # name: test-repo # default name of a out of the box default test Netlify CMS
  name: github
  repo: jonathanbell/gatsby-pro-level-up-tutorials-demo

media_folder: static/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: image, label: Image, widget: image }
