backend:
  # name: test-repo
  name: github
  repo: jonathanbell/gatsby-pro-level-up-tutorials-demo

media_folder: static/assets

collections:
  - name: post
    label: Posts
    folder: src/Posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: body, label: Post, widget: markdown }
